group = "com.softmaestri.flutter_rustore_miniapp_referer"
version = "1.0-SNAPSHOT"

buildscript {
    ext.kotlin_version = "2.2.20"
    repositories {
        google()
        mavenCentral()
        // https://www.rustore.ru/help/sdk/install-referrer/kotlin/7-0-0
        maven { url 'https://artifactory-external.vkpartner.ru/artifactory/maven' }
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.11.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // https://www.rustore.ru/help/sdk/install-referrer/kotlin/7-0-0
        maven { url 'https://artifactory-external.vkpartner.ru/artifactory/maven' }
    }
}

apply plugin: "com.android.library"
apply plugin: "kotlin-android"

android {
    namespace = "com.softmaestri.flutter_rustore_miniapp_referer"

    compileSdk = 35

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    defaultConfig {
        minSdk = 24
    }

    dependencies {
        // https://www.rustore.ru/help/sdk/install-referrer/kotlin/7-0-0
        implementation 'ru.rustore.sdk:installreferrer:10.0.0'

        testImplementation("org.jetbrains.kotlin:kotlin-test")
        testImplementation("org.mockito:mockito-core:5.0.0")
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}
